spring:
  application:
    name: meetudy

  datasource:
    hikari:
      maximum-pool-size: 20
    url: jdbc:mysql://localhost:3306/meetudy
    username: root
    password: database-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: clientId
            client-secret: clientSecret
            redirect-uri: "http://localhost:3000/oauth2/callback/kakao"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    host: smtp.gmail.com
    port: 587
    username: mail-username
    password: mail-password
    properties:
      mail.smtp.debug: true
      mail.smtp.timeout: 50000
      mail.starttls.enable: true
      mail.smtp.auth: true

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq-username
    password: rabbitmq-password

jwt:
  secret: jwtSecret

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true